<h2>Q1

In [3]:
import pandas as pd

data=pd.read_csv('Salary_Dataset.csv')

In [17]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           6704 non-null   int64  
 1   Age                  6702 non-null   float64
 2   Gender               6702 non-null   object 
 3   Education Level      6701 non-null   object 
 4   Job Title            6702 non-null   object 
 5   Years of Experience  6701 non-null   float64
 6   Salary               6699 non-null   float64
 7   Country              6704 non-null   object 
 8   Race                 6704 non-null   object 
dtypes: float64(3), int64(1), object(5)
memory usage: 471.5+ KB


In [18]:
young_employees = data[(data['Age'] < 35) & data['Years of Experience']]
young_employees['Salary'].count()
young_employees['Salary'].mean()
young_employees['Salary'].median()

85000.0

In [21]:
e1=data[data['Education Level']=="Bachelor's"]
e1['Salary'].count()
e1['Salary'].mean()
e1['Salary'].median()

130000.0

In [22]:
data_types = data.dtypes
numerical_features = data_types[data_types != 'object'].index.tolist()
categorical_features = data_types[data_types == 'object'].index.tolist()  #it retrieves the index labels and converts them into a regular Python list.

print("Numerical Features:")
print(numerical_features)
print("\nCategorical Features:")
print(categorical_features)


Numerical Features:
['Unnamed: 0', 'Age', 'Years of Experience', 'Salary']

Categorical Features:
['Gender', 'Education Level', 'Job Title', 'Country', 'Race']


<h2>Q2

In [26]:
import numpy as np

array=np.random.uniform(-4,4,size=25)

In [29]:
np.mean(array)
np.std(array)

2.518472972752062

In [32]:
symmetric_matrix=np.zeros((4,4))

upper_triangle = np.random.randint(1, 10, size=(4, 4))
upper_triangle = np.triu(upper_triangle, k=1)

symmetric_matrix += upper_triangle + upper_triangle.T  # Add the upper triangle and its transpose

print(symmetric_matrix)

[[0. 1. 3. 3.]
 [1. 0. 9. 9.]
 [3. 9. 0. 8.]
 [3. 9. 8. 0.]]
